import React from 'react';
import Head from 'next/head';

import { useAppContext } from '../context/appContext';
import Navbar from '../components/Navbar';
import SearchInput from '../components/SearchInput';
import Slider from '../components/Slider';
import MoviesList from '../components/MoviesList';
import { MainContainer } from '../styles/components';

const Home = () => {
  const { data, isLoading, isError, inputValue } = useAppContext();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navbar />
        {isLoading ? (
          <div>Loading...</div>
        ) : isError ? (
          <div>Something went wrong</div>
        ) : (
          <MainContainer>
            <SearchInput />
            {inputValue ? (
              <MoviesList
                data={data}
                title={`Found ${data.length > 0 ? data.length : 'no'} result${
                  data.length > 1 ? 's' : ''
                } for '${inputValue}'`}
              />
            ) : (
              <>
                <Slider data={data} />
                <MoviesList
                  data={data.filter((movie) => movie.isTrending === false)}
                  title='Recommended for you'
                />
              </>
            )}
          </MainContainer>
        )}
      </main>
    </>
  );
};

export default Home;
