import React from 'react';
import Head from 'next/head';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';

import { useAppContext } from '../context/appContext';
import Navbar from '../components/Navbar';
import SearchInput from '../components/SearchInput';
import TrendingMovieCard from '../components/TrendingMovieCard';
import BasicMovieCard from '../components/BasicMovieCard';

import {
  BasicMovieContainer,
  BasicSection,
  MainContainer,
} from '../styles/components';

const Home = () => {
  const { data, isLoading, isError } = useAppContext();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <Navbar />
        {isLoading ? (
          <div>Loading...</div>
        ) : isError ? (
          <div>Something went wrong</div>
        ) : (
          <MainContainer>
            <SearchInput />
            <BasicSection>
              <h2>Trending</h2>
              <Swiper
                slidesPerView={1}
                pagination={{ clickable: true }}
                style={{ marginTop: 24 }}
              >
                {data &&
                  data.trendingMovies.map((movie) => (
                    <SwiperSlide key={movie.title}>
                      <TrendingMovieCard {...movie} />
                    </SwiperSlide>
                  ))}
              </Swiper>
            </BasicSection>
            <BasicSection>
              <h2>Recommended for you</h2>
              <BasicMovieContainer>
                {data &&
                  data.recommendedMovies.map((movie) => (
                    <BasicMovieCard key={movie.title} {...movie} />
                  ))}
              </BasicMovieContainer>
            </BasicSection>
          </MainContainer>
        )}
      </div>
    </>
  );
};

export default Home;
