import React from 'react';
import Head from 'next/head';

import { useAppContext } from '../context/appContext';
import MoviesList from '../components/MoviesList';
import SearchInput from '../components/SearchInput';
import Navbar from '../components/Navbar';
import { MainContainer, SecondaryContainer } from '../styles/components';
import { connectToDatabase } from '../services/mongodb';

const Movies = ({ serverData }) => {
  const { data, inputValue } = useAppContext();

  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainContainer>
        <Navbar />
        <SecondaryContainer>
          <SearchInput placeholder={'Search for movies'} />
          {inputValue ? (
            <MoviesList
              data={data.filter((movie) => movie.category === 'Movie')}
              title={`Found ${data.length > 0 ? data.length : 'no'} result${
                data.length > 1 ? 's' : ''
              } for '${inputValue}'`}
            />
          ) : (
            <MoviesList data={serverData} title='Movies' />
          )}
        </SecondaryContainer>
      </MainContainer>
    </>
  );
};

export async function getServerSideProps(context) {
  const { db } = await connectToDatabase();
  const serverData = await db.collection('movies').find().toArray();
  console.log(serverData.length);

  return {
    props: {
      serverData: serverData
        .filter((item) => item.category === 'Movie')
        .map((item) => ({
          _id: item._id.toString(),
          title: item.title,
          category: item.category,
          isBookmarked: item.isBookmarked,
          isTrending: item.isTrending,
          rating: item.rating,
          year: item.year,
        })),
    },
  };
}

export default Movies;
