import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';

import Navbar from '../components/Navbar';
import SearchInput from '../components/SearchInput';
import TrendingMovieCard from '../components/TrendingMovieCard';
import BasicMovieCard from '../components/BasicMovieCard';

import {
  BasicMovieContainer,
  BasicSection,
  MainContainer,
} from '../styles/components';

const Home = () => {
  const [trendingMovies, setTrendingMovies] = useState([]);
  const [recommendedMovies, setRecommendedMovies] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isError, setIsError] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      setIsError(false);
      try {
        const response = await fetch('/api/home');
        const data = await response.json();

        setTrendingMovies(data.trendingMovies);
        setRecommendedMovies(data.recommendedMovies);
        setIsLoading(false);
      } catch (error) {
        setIsError(true);
      }
    };

    fetchData();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <Navbar />
        {isLoading ? (
          <div>Loading...</div>
        ) : isError ? (
          <div>Something went wrong</div>
        ) : (
          <MainContainer>
            <SearchInput />
            <BasicSection>
              <h2>Trending</h2>
              <Swiper
                slidesPerView={1}
                pagination={{ clickable: true }}
                style={{ marginTop: 24 }}
              >
                {trendingMovies.map((movie) => (
                  <SwiperSlide key={movie.title}>
                    <TrendingMovieCard {...movie} />
                  </SwiperSlide>
                ))}
              </Swiper>
            </BasicSection>
            <BasicSection>
              <h2>Recommended for you</h2>
              <BasicMovieContainer>
                {recommendedMovies.map((movie) => (
                  <BasicMovieCard key={movie.title} {...movie} />
                ))}
              </BasicMovieContainer>
            </BasicSection>
          </MainContainer>
        )}
      </div>
    </div>
  );
};

export default Home;
