import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import SearchInput from '../components/SearchInput';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <Link href='/home'>Home</Link>
      </div>
    </div>
  );
};

export default Home;
